export const MobilesData = [
    {
        id: 1,
        category: 'Mobiles',
        brand: 'apple',
        title: "Apple iPhone 14",
        imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
        amazonLink: 'https://amzn.to/3PuckZp',
        description: 'Apple iPhone 14 (128 GB) - Blue',
        price: '338',
    },
    {
        id: 2,
        category: 'Mobiles',
        brand: 'apple',
        title: "Apple iPhone 11",
        imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
        amazonLink: 'https://amzn.to/44MiYi6',
        description: 'Apple iPhone 11 (64GB) - White',
        price: '164',
    },
    {
        id: 3,
        category: 'Mobiles',
        brand: 'apple',
        title: "Apple iPhone 13",
        imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
        amazonLink: 'https://amzn.to/3r6XJtv',
        description: 'Apple iPhone 13 (128GB) - Blue',
        price: '224',
    },
    {
        id: 3,
        category: 'Mobiles',
        brand: 'samsung',
        title: "Galaxy S25 Edge",
        imgSrc: 'https://m.media-amazon.com/images/I/41f+unNiyjL._SY300_SX300_.jpg',
        //  amazonLink: 'https://amzn.to/3r6XJtv',
        description: 'Samsung Galaxy S25 Edge 5G AI Smartphone',
        price: '992',
    },
    {
        id: 3,
        category: 'Mobiles',
        brand: 'samsung',
        title: "Galaxy S25 Edge",
        imgSrc: 'https://m.media-amazon.com/images/I/41f+unNiyjL._SY300_SX300_.jpg',
        //  amazonLink: 'https://amzn.to/3r6XJtv',
        description: 'Samsung Galaxy S25 Edge 5G AI Smartphone',
        price: '992',
    },
    {
        id: 3,
        category: 'Mobiles',
        brand: 'samsung',
        title: "Galaxy S25 Edge",
        imgSrc: 'https://m.media-amazon.com/images/I/41f+unNiyjL._SY300_SX300_.jpg',
        //  amazonLink: 'https://amzn.to/3r6XJtv',
        description: 'Samsung Galaxy S25 Edge 5G AI Smartphone',
        price: '992',
    }
];
